apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: fullstacks.crossbow.jazz.io
spec:
  group: crossbow.jazz.io
  names:
    kind: FullStack
    plural: fullstacks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appName:
              type: string
            deployment:
              properties:
                metadata:
                  properties:
                    annotations:
                      type: object
                    labels:
                      type: object
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                replicas:
                  format: int32
                  type: integer
                selector:
                  properties:
                    appName:
                      type: string
                  required:
                  - appName
                  type: object
                strategy:
                  type: object
                template:
                  properties:
                    metadata:
                      properties:
                        annotations:
                          type: object
                        labels:
                          type: object
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                      - name
                      - namespace
                      type: object
                    podSpec:
                      type: object
                  required:
                  - metadata
                  - podSpec
                  type: object
              required:
              - selector
              - template
              - metadata
              type: object
            namespace:
              type: string
          required:
          - namespace
          - appName
          - deployment
          type: object
        status:
          properties:
            appName:
              type: string
            namespace:
              type: string
          required:
          - namespace
          - appName
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
